"""Initial

Revision ID: b0d675baa968
Revises: 
Create Date: 2026-09-15 18:31:04.267661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0d675baa968'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_code', sa.String(length=50), nullable=False),
    sa.Column('unit_name', sa.String(length=150), nullable=False),
    sa.Column('region_zone', sa.String(length=100), nullable=True),
    sa.Column('commander_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commander_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_id'), 'units', ['id'], unique=False)
    op.create_index(op.f('ix_units_unit_code'), 'units', ['unit_code'], unique=True)
    op.create_table('personnel_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('personnel_code', sa.String(length=100), nullable=False),
    sa.Column('rank', sa.String(length=50), nullable=False),
    sa.Column('service_years', sa.Integer(), nullable=True),
    sa.Column('age_band', sa.String(length=20), nullable=False),
    sa.Column('accommodation_type', sa.String(length=50), nullable=False),
    sa.Column('deployment_zone', sa.String(length=100), nullable=False),
    sa.Column('hardship_category', sa.String(length=10), nullable=False),
    sa.Column('days_deployed', sa.Integer(), nullable=True),
    sa.Column('days_in_hardship_A', sa.Integer(), nullable=True),
    sa.Column('zone_changes', sa.Integer(), nullable=True),
    sa.Column('distance_from_parent_unit_km', sa.Float(), nullable=True),
    sa.Column('rotation_notice_days', sa.Integer(), nullable=True),
    sa.Column('posting_duration_days', sa.Integer(), nullable=True),
    sa.Column('welfare_record_access', sa.String(length=20), nullable=False),
    sa.Column('device_consent_status', sa.String(length=20), nullable=False),
    sa.Column('self_report_consent', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_personnel_profiles_id'), 'personnel_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_personnel_profiles_personnel_code'), 'personnel_profiles', ['personnel_code'], unique=True)
    op.create_index(op.f('ix_personnel_profiles_unit_id'), 'personnel_profiles', ['unit_id'], unique=False)
    op.create_table('duty_hr_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('log_date', sa.Date(), nullable=True),
    sa.Column('duty_hours', sa.Float(), nullable=False),
    sa.Column('duty_days', sa.Integer(), nullable=True),
    sa.Column('rest_days', sa.Integer(), nullable=True),
    sa.Column('rest_interval_hours', sa.Float(), nullable=True),
    sa.Column('night_shift_count', sa.Integer(), nullable=True),
    sa.Column('max_consec_night_shifts', sa.Integer(), nullable=True),
    sa.Column('high_risk_duty_count', sa.Integer(), nullable=True),
    sa.Column('overtime_hours', sa.Float(), nullable=True),
    sa.Column('max_consec_duty_days', sa.Integer(), nullable=True),
    sa.Column('training_hours', sa.Float(), nullable=True),
    sa.Column('quick_turnaround_count', sa.Integer(), nullable=True),
    sa.Column('baseline_duty_hours', sa.Float(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duty_hr_logs_id'), 'duty_hr_logs', ['id'], unique=False)
    op.create_index(op.f('ix_duty_hr_logs_log_date'), 'duty_hr_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_duty_hr_logs_personnel_id'), 'duty_hr_logs', ['personnel_id'], unique=False)
    op.create_table('health_vitals_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=True),
    sa.Column('sleep_duration_hours', sa.Float(), nullable=True),
    sa.Column('sleep_min_hours', sa.Float(), nullable=True),
    sa.Column('max_consec_nights_below_5h', sa.Integer(), nullable=True),
    sa.Column('sleep_debt_7d', sa.Float(), nullable=True),
    sa.Column('sleep_quality_score', sa.Float(), nullable=True),
    sa.Column('sleep_onset_time', sa.Float(), nullable=True),
    sa.Column('sleep_timing_variability_7d', sa.Float(), nullable=True),
    sa.Column('fatigue_score', sa.Float(), nullable=True),
    sa.Column('recovery_score', sa.Float(), nullable=True),
    sa.Column('resting_heart_rate', sa.Float(), nullable=True),
    sa.Column('hrv_ms', sa.Float(), nullable=True),
    sa.Column('step_count', sa.Float(), nullable=True),
    sa.Column('mobility_radius_km', sa.Float(), nullable=True),
    sa.Column('baseline_sleep_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_vitals_logs_id'), 'health_vitals_logs', ['id'], unique=False)
    op.create_index(op.f('ix_health_vitals_logs_log_date'), 'health_vitals_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_health_vitals_logs_personnel_id'), 'health_vitals_logs', ['personnel_id'], unique=False)
    op.create_table('incident_discipline_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('sick_report_days', sa.Integer(), nullable=True),
    sa.Column('unplanned_absence_days', sa.Integer(), nullable=True),
    sa.Column('late_reporting_days', sa.Integer(), nullable=True),
    sa.Column('grievances_raised', sa.Integer(), nullable=True),
    sa.Column('safety_lapses', sa.Integer(), nullable=True),
    sa.Column('disciplinary_incidents', sa.Integer(), nullable=True),
    sa.Column('support_request', sa.Integer(), nullable=True),
    sa.Column('days_since_last_intervention', sa.Integer(), nullable=True),
    sa.Column('interventions_90d', sa.Integer(), nullable=True),
    sa.Column('last_intervention_effective', sa.Boolean(), nullable=True),
    sa.Column('workload_score', sa.Float(), nullable=True),
    sa.Column('cumulative_strain_load', sa.Float(), nullable=True),
    sa.Column('critical_incident_this_week', sa.Boolean(), nullable=True),
    sa.Column('critical_incidents_12m', sa.Integer(), nullable=True),
    sa.Column('days_since_critical_incident', sa.Integer(), nullable=True),
    sa.Column('transfers_12m', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_discipline_logs_id'), 'incident_discipline_logs', ['id'], unique=False)
    op.create_index(op.f('ix_incident_discipline_logs_personnel_id'), 'incident_discipline_logs', ['personnel_id'], unique=False)
    op.create_table('leave_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('leave_applications', sa.Integer(), nullable=True),
    sa.Column('leave_granted', sa.Integer(), nullable=True),
    sa.Column('leave_rejected', sa.Integer(), nullable=True),
    sa.Column('leave_cancelled_after_approval', sa.Integer(), nullable=True),
    sa.Column('leave_days_taken', sa.Integer(), nullable=True),
    sa.Column('emergency_leave_applications', sa.Integer(), nullable=True),
    sa.Column('days_notice_given', sa.Float(), nullable=True),
    sa.Column('days_since_last_leave', sa.Integer(), nullable=True),
    sa.Column('days_since_last_home_leave', sa.Integer(), nullable=True),
    sa.Column('consecutive_leave_rejections', sa.Integer(), nullable=True),
    sa.Column('rejection_rate_90d', sa.Float(), nullable=True),
    sa.Column('days_since_last_granted', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_records_id'), 'leave_records', ['id'], unique=False)
    op.create_index(op.f('ix_leave_records_personnel_id'), 'leave_records', ['personnel_id'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('prediction_timestamp', sa.DateTime(), nullable=False),
    sa.Column('burnout_score', sa.Float(), nullable=True),
    sa.Column('burnout_band', sa.String(length=50), nullable=True),
    sa.Column('burnout_severity', sa.String(length=50), nullable=True),
    sa.Column('strain_index', sa.Float(), nullable=True),
    sa.Column('strain_band', sa.String(length=50), nullable=True),
    sa.Column('strain_alert', sa.String(length=50), nullable=True),
    sa.Column('pss_score', sa.Float(), nullable=True),
    sa.Column('pss_band', sa.String(length=50), nullable=True),
    sa.Column('stress_score_est', sa.Float(), nullable=True),
    sa.Column('stress_band', sa.String(length=50), nullable=True),
    sa.Column('stress_level', sa.String(length=50), nullable=True),
    sa.Column('welfare_risk_label', sa.String(length=100), nullable=True),
    sa.Column('strain_flag', sa.Integer(), nullable=True),
    sa.Column('stress_flag', sa.Integer(), nullable=True),
    sa.Column('strain_delta_from_baseline', sa.Float(), nullable=True),
    sa.Column('strain_z_from_baseline', sa.Float(), nullable=True),
    sa.Column('baseline_alert_flag', sa.Integer(), nullable=True),
    sa.Column('strain_trend_3w', sa.Float(), nullable=True),
    sa.Column('trend_flag', sa.String(length=50), nullable=True),
    sa.Column('intervention_recommended', sa.String(length=100), nullable=True),
    sa.Column('baseline_duty_hours', sa.Float(), nullable=True),
    sa.Column('baseline_sleep_hours', sa.Float(), nullable=True),
    sa.Column('baseline_strain_mean', sa.Float(), nullable=True),
    sa.Column('baseline_strain_sd', sa.Float(), nullable=True),
    sa.Column('welfare_incident', sa.Integer(), nullable=True),
    sa.Column('welfare_incident_next_week', sa.Float(), nullable=True),
    sa.Column('is_high_risk', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_predictions_id'), 'ml_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_ml_predictions_is_high_risk'), 'ml_predictions', ['is_high_risk'], unique=False)
    op.create_index(op.f('ix_ml_predictions_personnel_id'), 'ml_predictions', ['personnel_id'], unique=False)
    op.create_index(op.f('ix_ml_predictions_prediction_timestamp'), 'ml_predictions', ['prediction_timestamp'], unique=False)
    op.create_table('pvt_cognitive_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('cognitive_test_completed', sa.Boolean(), nullable=True),
    sa.Column('pvt_trials', sa.Float(), nullable=True),
    sa.Column('pvt_response_speed', sa.Float(), nullable=True),
    sa.Column('pvt_mean_rt_ms', sa.Float(), nullable=True),
    sa.Column('pvt_lapses', sa.Float(), nullable=True),
    sa.Column('pvt_false_starts', sa.Float(), nullable=True),
    sa.Column('pvt_fastest10_rt_ms', sa.Float(), nullable=True),
    sa.Column('pvt_slowest10_rt_ms', sa.Float(), nullable=True),
    sa.Column('baseline_pvt_lapses', sa.Float(), nullable=True),
    sa.Column('baseline_pvt_response_speed', sa.Float(), nullable=True),
    sa.Column('pvt_lapses_z', sa.Float(), nullable=True),
    sa.Column('pvt_speed_z', sa.Float(), nullable=True),
    sa.Column('test_time_of_day', sa.Float(), nullable=True),
    sa.Column('test_duration_s', sa.Float(), nullable=True),
    sa.Column('test_interrupted', sa.Boolean(), nullable=True),
    sa.Column('test_effort_flag', sa.Boolean(), nullable=True),
    sa.Column('days_since_last_test', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pvt_cognitive_tests_id'), 'pvt_cognitive_tests', ['id'], unique=False)
    op.create_index(op.f('ix_pvt_cognitive_tests_personnel_id'), 'pvt_cognitive_tests', ['personnel_id'], unique=False)
    op.create_table('who5_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('who5_score', sa.Float(), nullable=True),
    sa.Column('who5_assessment_due', sa.Boolean(), nullable=True),
    sa.Column('who5_response_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_who5_assessments_id'), 'who5_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_who5_assessments_personnel_id'), 'who5_assessments', ['personnel_id'], unique=False)
    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_id'], ['ml_predictions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventions_assigned_by_user_id'), 'interventions', ['assigned_by_user_id'], unique=False)
    op.create_index(op.f('ix_interventions_id'), 'interventions', ['id'], unique=False)
    op.create_index(op.f('ix_interventions_personnel_id'), 'interventions', ['personnel_id'], unique=False)
    op.add_column('users', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'units', ['unit_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'unit_id')
    op.drop_index(op.f('ix_interventions_personnel_id'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_id'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_assigned_by_user_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_who5_assessments_personnel_id'), table_name='who5_assessments')
    op.drop_index(op.f('ix_who5_assessments_id'), table_name='who5_assessments')
    op.drop_table('who5_assessments')
    op.drop_index(op.f('ix_pvt_cognitive_tests_personnel_id'), table_name='pvt_cognitive_tests')
    op.drop_index(op.f('ix_pvt_cognitive_tests_id'), table_name='pvt_cognitive_tests')
    op.drop_table('pvt_cognitive_tests')
    op.drop_index(op.f('ix_ml_predictions_prediction_timestamp'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_personnel_id'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_is_high_risk'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_id'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_leave_records_personnel_id'), table_name='leave_records')
    op.drop_index(op.f('ix_leave_records_id'), table_name='leave_records')
    op.drop_table('leave_records')
    op.drop_index(op.f('ix_incident_discipline_logs_personnel_id'), table_name='incident_discipline_logs')
    op.drop_index(op.f('ix_incident_discipline_logs_id'), table_name='incident_discipline_logs')
    op.drop_table('incident_discipline_logs')
    op.drop_index(op.f('ix_health_vitals_logs_personnel_id'), table_name='health_vitals_logs')
    op.drop_index(op.f('ix_health_vitals_logs_log_date'), table_name='health_vitals_logs')
    op.drop_index(op.f('ix_health_vitals_logs_id'), table_name='health_vitals_logs')
    op.drop_table('health_vitals_logs')
    op.drop_index(op.f('ix_duty_hr_logs_personnel_id'), table_name='duty_hr_logs')
    op.drop_index(op.f('ix_duty_hr_logs_log_date'), table_name='duty_hr_logs')
    op.drop_index(op.f('ix_duty_hr_logs_id'), table_name='duty_hr_logs')
    op.drop_table('duty_hr_logs')
    op.drop_index(op.f('ix_personnel_profiles_unit_id'), table_name='personnel_profiles')
    op.drop_index(op.f('ix_personnel_profiles_personnel_code'), table_name='personnel_profiles')
    op.drop_index(op.f('ix_personnel_profiles_id'), table_name='personnel_profiles')
    op.drop_table('personnel_profiles')
    op.drop_index(op.f('ix_units_unit_code'), table_name='units')
    op.drop_index(op.f('ix_units_id'), table_name='units')
    op.drop_table('units')
    # ### end Alembic commands ###
