"""Add hashed_password

Revision ID: 701c258842f9
Revises: b0d675baa968
Create Date: 2026-09-15 18:32:26.849048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '701c258842f9'
down_revision: Union[str, Sequence[str], None] = 'b0d675baa968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.alter_column('users', 'supabase_user_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'supabase_user_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
